# typescript
## syntax highlight
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']
## syntax highlight for JSX in Typescript
[[plugins]]
repo = 'peitalin/vim-jsx-typescript'

[[plugins]]
repo = 'Shougo/defx.nvim'
 
hook_add = '''
nnoremap <silent> <C-n> :<C-U> Defx <CR>
 
autocmd FileType defx call s:defx_my_settings()
function! s:defx_my_settings() abort
  " Define mappings
  nnoremap <silent><buffer><expr> <CR>
  \ defx#is_directory() ?
  \ defx#do_action('open_tree', 'recursive:1') :
  \ defx#do_action('open')
  nnoremap <silent><buffer><expr> t
  \ defx#do_action('open','tabnew')
  nnoremap <silent><buffer><expr> o
  \ match(bufname('%'), 'explorer') >= 0 ?
  \ (defx#is_directory() ? 0 : defx#do_action('drop', 'vsplit')) :
  \ (defx#is_directory() ? 0 : defx#do_action('multi', ['open', 'quit']))
  nnoremap <silent><buffer><expr> l
  \ defx#is_directory() ? defx#do_action('open') : 0
  nnoremap <silent><buffer><expr> h
  \ defx#do_action('cd', ['..'])
  nnoremap <silent><buffer><expr> K
  \ defx#do_action('new_directory')
  nnoremap <silent><buffer><expr> N
  \ defx#do_action('new_file')
  nnoremap <silent><buffer><expr> d
  \ defx#do_action('remove')
  nnoremap <silent><buffer><expr> r
  \ defx#do_action('rename')
  nnoremap <silent><buffer><expr> yy
  \ defx#do_action('yank_path')
  nnoremap <silent><buffer><expr> q
  \ defx#do_action('quit')
endfunction
'''
 
hook_post_source = '''
call defx#custom#column('git', 'indicators', {
  \ 'Modified'  : '✹',
  \ 'Staged'    : '✚',
  \ 'Untracked' : '✭',
  \ 'Renamed'   : '➜',
  \ 'Unmerged'  : '',
  \ 'Ignored'   : '☒',
  \ 'Deleted'   : '✖',
  \ 'Unknown'   : '?'
  \ })
call defx#custom#column('filename', {
  \ 'min_width': 40,
  \ 'max_width': 40,
  \ })
call defx#custom#option('_', {
  \ 'winwidth': 50,
  \ 'ignored_files': '.*,target*',
  \ 'direction': 'topleft',
  \ 'toggle': 1,
  \ 'resume': 1,
  \ 'columns': 'indent:git:icons:filename:mark',
  \ })
autocmd BufWritePost * call defx#redraw()
autocmd BufEnter * call defx#redraw()
'''
