# ファイラー
[[plugins]]
repo = 'lambdalisue/fern.vim'
depends = ['fern-renderer-nerdfont.vim']
hook_add = '''
  source ~/.config/nvim/plugins/fern.vim
'''


[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
depends = ['nerdfont.vim']

[[plugins]]
repo = 'kannokanno/previm'
hook_add = '''
  let g:previm_open_cmd = 'open -a Google\ Chrome'
'''
