# typescript
## syntax highlight
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']
## syntax highlight for JSX in Typescript
[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
# toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

# json
[[plugins]]
repo = 'elzr/vim-json'
hook_add = '''
  let g:vim_json_syntax_conceal = 0
'''
on_ft = ['json']

# ディレクトリーツリーを表示
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  source ~/.config/nvim/plugins/nerdtree.vim
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'
# download icon
# mkdir -p ~/.local/share/fonts
# cd ~/.local/share/fonts && curl -fLo "Droid Sans Mono for Powerline Nerd Font Complete.otf" https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete.otf
