# typescript
## syntax highlight
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']
## syntax highlight for JSX in Typescript
[[plugins]]
repo = 'peitalin/vim-jsx-typescript'

# ファイラー
[[plugins]]
repo = 'lambdalisue/fern.vim'
depends = ['fern-renderer-nerdfont.vim']
hook_add = '''
  source ~/.config/nvim/plugins/fern.vim
'''


[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
depends = ['nerdfont.vim']

