[[plugins]]
repo = 'Shougo/dein.vim'

# colorscheme
[[plugins]]
repo = 'ghifarit53/tokyonight-vim'
hook_add = '''
  let g:tokyonight_transparent_background = 1
  let g:tokyonight_enable_italic = 1
  colorscheme tokyonight
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'

[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = '''
  source ~/.config/nvim/plugins/coc.vim
'''

# git 差分表示
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  source ~/.config/nvim/plugins/gitgutter.vim
'''

# git操作をvim内で
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  source ~/.config/nvim/plugins/fugitive.vim
'''

# 最新のneovimでエラーになるため一旦コメントアウト
# [[plugins]]
# repo = 'f-person/git-blame.nvim'

[[plugins]]
repo = 'shumphrey/fugitive-gitlab.vim'
hook_add = '''
  source ~/.config/nvim/plugins/fugitive-gitlab.vim
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/denite.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  source ~/.config/nvim/plugins/airline.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

# tab manager
[[plugins]]
repo = 'romgrk/barbar.nvim'
hook_add = '''
 source ~/.config/nvim/plugins/barbar.vim
'''

# 自動コメントアウト
[[plugins]]
repo = 'tyru/caw.vim'

# interacting with databases
[[plugins]]
repo = 'tpope/vim-dadbod'

[[plugins]]
repo = 'kristijanhusak/vim-dadbod-ui'

# fuzzy finder
# fzf
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0
